name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and package (macOS)
        if: matrix.os == 'macos-latest'
        env:
          # Skip code signing - builds will be unsigned
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: |
          npm run make
          
      - name: Build and package (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          npm run make

      - name: Build and package (Windows)
        if: matrix.os == 'windows-latest'
        env:
          # Skip code signing - builds will be unsigned
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: |
          npm run make

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/make/**/*.dmg
            out/make/**/*.zip
            out/make/**/*.deb
            out/make/**/*.rpm
            out/make/**/*.exe
            out/make/**/*.msi
            out/make/**/*.AppImage
            out/make/**/*.yml
            out/make/**/*.blockmap
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
